### ISSUE TITLE
Callback not working :\

### ISSUE THREAD

**Issue by kirkstrobeck** [heroku/starboard#4]
I’m in a loop on this screen

![screen shot 2014-08-06 at 10 52 11 am](https://cloud.githubusercontent.com/assets/241963/3831403/112285ec-1d93-11e4-9266-cc5db539d4d3.png)

**Comment by lorn** [comment]
I had the same problem, and the heroku logs show this error:

```
2015-02-03T19:10:59.590627+00:00 app[web.1]: URI::InvalidURIError - bad URI(is not URI?): https://: ad7d1ffb37e37c2cf96514f5f2dd3851d4a1d496@api.github.com/repos/lorn-movile/starboard-docs-template/zipball/master:
```

I fix the problem giving my github token ALL acess that was possible, and it worked. I just want to take a look and feel of starboard :+1:

**Comment by ys** [comment]
Pretty sure the space at the beginning of the password is the issue there at least for the error mentioned.

Do not hesitate to open a new issue if you find something different but repo is really the only thing that it needs to access
